renaming and fixing

diff --git a/.github/workflows/cd-deploy.yaml b/.github/workflows/cd-deploy.yaml
--- a/.github/workflows/cd-deploy.yaml
+++ b/.github/workflows/cd-deploy.yaml
@@ -3,7 +3,7 @@ name: Deploy Docker Image
 on:
   workflow_call:
     inputs:
-      link-tag:
+      new-tag:
         type: string
         required: true
       gitops-file:
@@ -55,12 +55,12 @@ jobs:
         if: ${{ inputs.environment == 'prod' && inputs.rollback == false }}
         run: |
           echo "Current version: ${{ steps.get-tag.outputs.current-tag }}"
-          echo "New version: ${{ inputs.link-tag }}"
+          echo "New version: ${{ inputs.new-tag }}"
           npm install semver
-          is_valid=$(npx semver -r ">=$(echo "${{ steps.get-tag.outputs.current-tag }}")" "${{ inputs.link-tag }}")
+          is_valid=$(npx semver -r ">=$(echo "${{ steps.get-tag.outputs.current-tag }}")" "${{ inputs.new-tag }}")
       
           if [ -z "$is_valid" ]; then
-            echo "ERROR: New version ${{ inputs.link-tag }} is not greater or equal to current ${{ steps.get-tag.outputs.current-tag }}"
+            echo "ERROR: New version ${{ inputs.new-tag }} is not greater or equal to current ${{ steps.get-tag.outputs.current-tag }}"
             exit 1
           else
             echo "New version is valid (>= current)"
@@ -68,34 +68,34 @@ jobs:
 
       - name: Update GitOps file and release tag
         run: |
-          if [[ -z "${{ inputs.link-tag }}" ]]; then
+          if [[ -z "${{ inputs.new-tag }}" ]]; then
             echo "No Tag provided. Exiting."
             exit 1
           fi
           echo "Updating GitOps file: ${{ inputs.gitops-file }}"
           echo "image: $GITHUB_REPOSITORY" > "${{ inputs.gitops-file }}"
-          echo "tag: ${{ inputs.link-tag }}" >> "${{ inputs.gitops-file }}"          
+          echo "tag: ${{ inputs.new-tag }}" >> "${{ inputs.gitops-file }}"          
           echo "app: ${GITHUB_REPOSITORY##*/}" >> "${{ inputs.gitops-file }}"
           echo "replicas: ${{ inputs.replicas }}" >> "${{ inputs.gitops-file }}"          
           git add "${{ inputs.gitops-file }}"
           git fetch origin --tags ${{ github.ref_name }}
           git merge origin/${{ github.ref_name }}
-          git commit -m "github-actions[bot] deployed image $GITHUB_REPOSITORY:${{ inputs.link-tag }} to ${{ inputs.environment }}" || echo "No changes to commit"
+          git commit -m "github-actions[bot] deployed image $GITHUB_REPOSITORY:${{ inputs.new-tag }} to ${{ inputs.environment }}" || echo "No changes to commit"
           if [[ ${{ inputs.environment }} == 'preprod' ]]; then
-            if git rev-parse "${{ inputs.link-tag }}" >/dev/null 2>&1; then
-              echo "Tag '${{ inputs.link-tag }}' already exists. Exiting."
+            if git rev-parse "${{ inputs.new-tag }}" >/dev/null 2>&1; then
+              echo "Tag '${{ inputs.new-tag }}' already exists. Exiting."
               exit 1
             fi
-            git tag "${{ inputs.link-tag }}"
+            git tag "${{ inputs.new-tag }}"
             git push || echo "No changes to push"
-            git push origin "${{ inputs.link-tag }}" || echo "No tags to push tag"          
+            git push origin "${{ inputs.new-tag }}" || echo "No tags to push tag"          
           fi
           git push || echo "No changes to push"
           echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
 
       - name: Print summary
-        if: ${{ inputs.link-tag != steps.get-tag.outputs.current-tag }}
+        if: ${{ inputs.new-tag != steps.get-tag.outputs.current-tag }}
         run: |
           echo '### CD Action:' >> $GITHUB_STEP_SUMMARY
-            echo "Pushed image $GITHUB_REPOSITORY:${{ inputs.link-tag }} to ${{ inputs.environment }}" GitOps>> $GITHUB_STEP_SUMMARY
+            echo "Pushed image $GITHUB_REPOSITORY:${{ inputs.new-tag }} to ${{ inputs.environment }}" GitOps>> $GITHUB_STEP_SUMMARY
             echo "[View Commit](https://github.com/$GITHUB_REPOSITORY/commit/$COMMIT_SHA)" >> $GITHUB_STEP_SUMMARY
